---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Create Nginx configuration for proxy
  template:
    src: app.conf.j2
    dest: /etc/nginx/sites-available/app.conf
  become: yes
  notify: restart nginx

- name: Enable Nginx configuration
  file:
    src: /etc/nginx/sites-available/app.conf
    dest: /etc/nginx/sites-enabled/app.conf
    state: link
  become: yes
  notify: restart nginx

- name: Remove default Nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes
  notify: restart nginx

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
